name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    env:
      Email__ApiKey: ${{ secrets.FINTUREST__EMAIL__APIKEY }}
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
            3.1.x
            5.0.x
            6.0.x
            7.0.x
            8.0.x
            9.0.x

    - name: Build
      run: dotnet build Finturest.Email.sln --configuration Release /p:ContinuousIntegrationBuild=true

    - name: Integration tests
      run: dotnet test tests/Finturest.Email.IntegrationTests --configuration Release --no-build
      
    - name: Pack Finturest.Email
      run: dotnet pack src/Finturest.Email --configuration Release --no-build --output nuget

    - name: Pack Finturest.Email.Abstractions
      run: dotnet pack src/Finturest.Email.Abstractions --configuration Release --no-build --output nuget

    - name: Upload artifacts
      if: github.ref == 'refs/heads/master'
      uses: actions/upload-artifact@v4
      with:
        name: nuget
        path: nuget/
